### ISSUE TITLE
tcp 통신으로 데이터 전송을 하다가 발견한 이슈 

### ISSUE THREAD

**Issue by ksk2811** [ksk2811/apm#10]
tcp 통신으로 데이터 전송을 하다가 발견한 이슈

tpc 서버는 php로 만들어졌으며 고전 방식인  fork 를 이용해  멀티 프로세스를 지원하고 있는 상태.

아래는 테스트 과정

1) php 서버생성 (php  ./daemon.v4.php)

2) tcp 통신을 위해 쉘에서 아래 명령어 수행 (브라우저에서 접속해도 동일)
   $> telnet localhost 8888
   $> 데이터 입력

3) php 서버에서 최초 커넥션 생성되면
    fork 로 child process를 생성하여 데이터를 수신하고 종료
    parent process는 동일하게 accept 과정을 거침

4) 문제는 child process가 데이터 수신후 종료하게 되면
    PHP_RSHUTDOWN_FUNCTION 에  등록된 데이터 전송 로직이 실행되면서
   다시 php 서버에 커넥션 시도

5) fork 로 child process를 생성하여 데이터를 수신하고
    parent process는 동일하게 accept 과정을 거침

4~5 과정이 무한 반복하는 이슈가 있음
일반적으로 php로 tcp 서버를 만드는 일은 거의 없겠지만
지금처럼 테스트로는 충분히 만들어서 사용할 가능성이 있기때문에

실무에서 이런일이 발생한적이 있는지 확인 필요

**Comment by whatapdev** [comment]
udp는 packet 방식이고, tcp 는 streaming 방식 입니다. 
두 방식의 차이점과 , tcp multi client 방식을  확인해 보시면 좋을 것 같습니다.

**Comment by ksk2811** [comment]
예 답변 감사합니다.
이거는 서버를 분리하던지 해서 처리를 해볼게요
