### ISSUE TITLE
php 내부 malloc 함수를 잘 못 알려드렸네요. p 로 시작하는 게 아니라 emalloc, efree 입니다. 

### ISSUE THREAD

**Issue by whatapdev** [ksk2811/apm#13]

**Comment by ksk2811** [comment]
네 우선은 pemalloc은 정확히 어떤식으로 작동하는지 몰라서 안썻고
php소스에서도 malloc과  emalloc을 혼용해서 사용하고 있는데
정확한 차이를 몰라서 우선 malloc으로 개발한 상태입니다.

**Comment by ksk2811** [comment]
넵 알려주신 함수 확인해서 수정하도록 하겠습니다.
