### ISSUE TITLE
[0003]  페이지 호출시 실행하는 코드 별도의 파일로 분리

### ISSUE THREAD

**Issue by ksk2811** [ksk2811/apm#3]
- todo: 시간, 종료 순간의 로직을 별도의 파일로
      빼서 함수로 구현하려 했으나 일반적인 c 의
      방식으로는 안됨

**Comment by hammaa** [comment]
config.m4 파일 내부  PHP_NEW_EXTENSION(apm, apm.c, $ext_shared)

**Comment by ksk2811** [comment]
완료!
